# Generated by Django 4.2.7 on 2023-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0003_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('is_visible', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
        migrations.AddField(
            model_name='dish',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='with_discount',
            field=models.BooleanField(default=False),
        ),
    ]
